# Generated by Django 4.2.6 on 2023-10-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0002_alter_item_description_alter_item_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='links',
        ),
        migrations.AddField(
            model_name='item',
            name='links',
            field=models.ManyToManyField(blank=True, to='concepts.item'),
        ),
    ]
