# Generated by Django 4.2.6 on 2023-10-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concepts", "0004_alter_item_description_alter_item_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["name", "source", "identifier"]},
        ),
        migrations.AlterField(
            model_name="item",
            name="source",
            field=models.CharField(
                choices=[
                    ("Wd", "Wikidata"),
                    ("nL", "nLab"),
                    ("MW", "MathWorld"),
                    ("WpEN", "Wikipedia (English)"),
                    ("AUm", "Agda Unimath"),
                ],
                max_length=4,
            ),
        ),
    ]
