# Generated by Django 4.2.6 on 2023-11-17 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("concepts", "0005_alter_item_options_alter_item_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="links",
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("Wd", "Wikidata"),
                            ("AUm", "Agda Unimath"),
                            ("eq", "same name"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_items",
                        to="concepts.item",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_items",
                        to="concepts.item",
                    ),
                ),
            ],
            options={
                "ordering": ["source", "destination", "label"],
                "unique_together": {("source", "destination", "label")},
            },
        ),
    ]
