# Generated by Django 4.2.6 on 2023-11-18 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("concepts", "0006_remove_item_links_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True, unique=True)),
                ("description", models.TextField(null=True)),
            ],
            options={
                "ordering": ["name", "description"],
            },
        ),
        migrations.AddField(
            model_name="item",
            name="concept",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="concepts.concept",
            ),
        ),
    ]
