# Generated by Django 4.2.6 on 2023-11-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concepts", "0008_alter_concept_name_concept_unique_lower_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="source",
            field=models.CharField(
                choices=[
                    ("Wd", "Wikidata"),
                    ("nL", "nLab"),
                    ("MW", "MathWorld"),
                    ("PW", "ProofWiki"),
                    ("WpEN", "Wikipedia (English)"),
                    ("AUm", "Agda Unimath"),
                ],
                max_length=4,
            ),
        ),
    ]
