# Generated by Django 4.2.25 on 2025-12-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concepts", "0010_alter_item_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="keywords",
            field=models.TextField(blank=True, null=True),
        ),
    ]
