# Generated by Django 4.2.25 on 2025-12-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concepts", "0011_item_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="article_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
