# Generated by Django 4.2.25 on 2025-12-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concepts", "0012_item_article_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="aliases",
            field=models.TextField(blank=True, null=True),
        ),
    ]
