# Generated by Django 4.2.25 on 2025-12-11 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("concepts", "0013_item_aliases"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorizerResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("llm_type", models.CharField(max_length=50)),
                ("raw_result", models.TextField()),
                ("result_answer", models.BooleanField()),
                ("result_confidence", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorizer_results",
                        to="concepts.item",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["item", "llm_type"],
                        name="concepts_ca_item_id_c24595_idx",
                    ),
                    models.Index(
                        fields=["result_answer"], name="concepts_ca_result__a4c7a5_idx"
                    ),
                    models.Index(
                        fields=["result_confidence"],
                        name="concepts_ca_result__d25f96_idx",
                    ),
                ],
            },
        ),
    ]
