# Generated by Django 4.2.27 on 2025-12-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concepts", "0014_categorizerresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorizerresult",
            name="llm_type",
            field=models.CharField(max_length=100),
        ),
    ]
