# Generated by Django 4.2.27 on 2026-03-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concepts", "0014_categorizerresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorizerresult",
            name="reasoning",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="categorizerresult",
            name="session_name",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="categorizerresult",
            name="llm_type",
            field=models.CharField(max_length=100),
        ),
    ]
