# Generated by Django 4.2.28 on 2026-03-31 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concepts", "0015_add_session_name_to_categorizerresult"),
        ("concepts", "0015_alter_categorizerresult_llm_type"),
    ]

    operations = []
