# Generated by Django 4.2.27 on 2026-04-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concepts", "0016_merge_20260331_0904"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="domain",
            field=models.CharField(
                choices=[("math", "Mathematics"), ("phys", "Physics")],
                default="math",
                max_length=4,
            ),
        ),
    ]
