# Generated by Django 4.2.27 on 2026-04-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concepts", "0017_item_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="meta",
            field=models.TextField(blank=True, null=True),
        ),
    ]
