# Generated by Django 4.2.29 on 2026-04-09 16:46

from django.db import migrations, models

from concepts.utils import normalize_concept_name


def forward(apps, schema_editor):
    Concept = apps.get_model("concepts", "Concept")
    to_update = []
    for c in Concept.objects.all():
        c.normal_name = normalize_concept_name(c.name)
        to_update.append(c)
    Concept.objects.bulk_update(to_update, ["normal_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("concepts", "0018_item_meta"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="concept",
            name="unique_lower_name",
        ),
        migrations.AddField(
            model_name="concept",
            name="normal_name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name="concept",
            constraint=models.UniqueConstraint(
                fields=("normal_name",), name="unique_normal_name"
            ),
        ),
        migrations.RunPython(forward, lambda *_args: None),
    ]
