# Generated by Django 4.2.28 on 2026-04-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0019_remove_concept_unique_lower_name_concept_normal_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='source',
            field=models.CharField(choices=[('Wd', 'Wikidata'), ('nL', 'nLab'), ('MW', 'MathWorld'), ('PW', 'ProofWiki'), ('EoM', 'Encyclopedia of Mathematics'), ('WpEN', 'Wikipedia (English)'), ('AUm', 'Agda Unimath'), ('LMF', 'The L-functions and modular forms database')], max_length=4),
        ),
    ]
