# Generated by Django 4.2.28 on 2026-04-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0020_alter_item_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='identifier',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(max_length=300),
        ),
    ]
