# Generated by Django 4.2.30 on 2026-08-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concepts", "0022_concept_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="source",
            field=models.CharField(
                choices=[
                    ("Wd", "Wikidata"),
                    ("nL", "nLab"),
                    ("MW", "MathWorld"),
                    ("PW", "ProofWiki"),
                    ("EoM", "Encyclopedia of Mathematics"),
                    ("WpEN", "Wikipedia (English)"),
                    ("AUm", "Agda Unimath"),
                    ("LMF", "The L-functions and modular forms database"),
                    ("HoG", "House of Graphs"),
                ],
                max_length=4,
            ),
        ),
    ]
