# Generated by Django 4.2.28 on 2026-04-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlurperRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=8, unique=True)),
                ('last_succeeded_at', models.DateTimeField()),
            ],
        ),
    ]
