"""Parse mathlib4 .lean sources into docstrings and approximate reference counts.

This is a regex-level approximation, not a Lean elaborator:
- full names are rebuilt from `namespace` / `section` / `end` scopes;
- declarations generated by attributes (`to_additive`, `simps`, ...) and
  derived instances are not seen, so they have no docstring here;
- a reference is a code token (comments and docstrings excluded) that resolves
  to a candidate name either directly or through an `open`ed / enclosing
  namespace of the same file; dot-notation (`hp.two_le`) is not resolved.
"""

import json
import re
from collections import defaultdict

import config
from universe import load_universe

# --- lexing -----------------------------------------------------------------

_SPECIAL = re.compile(r'"|--|/-')


def _skip_block(text, i):
    """Return the index after the block comment opened at text[i:i+2] == '/-'."""
    depth = 1
    i += 2
    n = len(text)
    while i < n and depth:
        j = text.find("-/", i)
        k = text.find("/-", i)
        if j < 0:
            return n
        if 0 <= k < j:
            depth += 1
            i = k + 2
        else:
            depth -= 1
            i = j + 2
    return i


def split_code(text):
    """Split Lean source into (code, docstrings).

    `code` has every comment, docstring and string literal removed; each
    docstring is replaced by a placeholder `\\x00DOC<n>\\x00` so the declaration
    regex can see where it was. `docstrings` is the list of their contents.
    """
    out = []
    docs = []
    i = 0
    n = len(text)
    while i < n:
        m = _SPECIAL.search(text, i)
        if not m:
            out.append(text[i:])
            break
        start = m.start()
        out.append(text[i:start])
        tok = m.group()
        if tok == '"':
            j = start + 1
            while j < n and text[j] != '"':
                j += 2 if text[j] == "\\" else 1
            out.append('""')
            i = j + 1
        elif tok == "--":
            j = text.find("\n", start)
            i = n if j < 0 else j
        else:  # "/-"
            end = _skip_block(text, start)
            if text.startswith("/--", start) and not text.startswith("/--/", start):
                body_start, body_end = start + 3, end - 2
                docs.append(text[body_start:body_end].strip())
                out.append(f" \x00DOC{len(docs) - 1}\x00 ")
            else:
                out.append(" ")
            i = end
    return "".join(out), docs


# --- declarations and scopes ------------------------------------------------

_IDENT = r"[^\s:(){}\[\]⦃⦄,@\x00\"]+"
_ATTRS = r"(?:@\[(?:[^\[\]]|\[(?:[^\[\]]|\[[^\[\]]*\])*\])*\]\s*)*"
_MODS = r"(?:(?:private|protected|public|noncomputable|unsafe|partial|nonrec|meta)\s+)*"
_KEYWORDS = (
    r"class\s+inductive|class\s+abbrev|irreducible_def|def|abbrev|theorem|lemma|"
    r"instance|structure|class|inductive|opaque|axiom"
)

_EVENT = re.compile(
    rf"""^[ \t]*(?:
      (?P<decl>
        (?:\x00DOC(?P<doc>\d+)\x00\s*)?
        (?P<attrs>{_ATTRS})
        {_MODS}
        (?P<kw>{_KEYWORDS})\s+
        (?:\(priority\s*:=[^)]*\)\s*)?
        (?P<name>{_IDENT})
      )
    | (?P<scope>(?:@\[[^\]]*\]\s*)?(?:(?:public|private|noncomputable|meta)\s+)*
         (?P<scopekw>namespace|section|end)\b[ \t]*(?P<scopename>[^\s]*))
    | (?P<open>open\b(?:\s+scoped)?(?P<opennames>[^\n]*))
    )""",
    re.MULTILINE | re.VERBOSE,
)

_ADDITIVE_DOC = re.compile(r"to_additive\b[^\]]*?(?:\x00DOC\d+\x00|\"\")")
_WIKIDATA = re.compile(r"\bwikidata\s+(Q\d+)")
_DOC_IN_ATTR = re.compile(r"\x00DOC(\d+)\x00")
_TOKEN = re.compile(r"[^\W\d][\w'!?₀-₉ᵢ-ᵪ]*(?:\.[^\W\d][\w'!?₀-₉ᵢ-ᵪ]*)*")
_OPEN_STOP = {"in", "hiding", "renaming", "scoped"}


def _split_name(name):
    return [part for part in name.split(".") if part]


def parse_file(text):
    """Parse one .lean file.

    Returns (decls, code, namespaces) where decls is a list of dicts
    {name, kind, doc, additive_doc, wikidata}, code is the comment-free source
    and namespaces is every namespace/open prefix active somewhere in the file.
    """
    code, docs = split_code(text)
    stack = []  # list of (kind, [components])
    namespaces = set()
    decls = []
    for m in _EVENT.finditer(code):
        if m.group("decl"):
            name = m.group("name").rstrip(".")
            if name.startswith("_root_."):
                full = name.removeprefix("_root_.")
            else:
                prefix = [c for kind, comps in stack if kind == "ns" for c in comps]
                full = ".".join(prefix + [name])
            attrs = m.group("attrs") or ""
            doc_id = m.group("doc")
            additive = None
            if "to_additive" in attrs:
                am = _ADDITIVE_DOC.search(attrs)
                if am:
                    dm = _DOC_IN_ATTR.search(am.group())
                    additive = docs[int(dm.group(1))] if dm else ""
            wd = _WIKIDATA.search(attrs)
            decls.append(
                {
                    "name": full,
                    "kind": re.sub(r"\s+", " ", m.group("kw")),
                    "doc": docs[int(doc_id)] if doc_id is not None else None,
                    "to_additive": "to_additive" in attrs,
                    "additive_doc": additive,
                    "wikidata": wd.group(1) if wd else None,
                }
            )
        elif m.group("scope"):
            kw = m.group("scopekw")
            comps = _split_name(m.group("scopename"))
            if kw == "namespace":
                stack.append(("ns", comps))
                full = [c for kind, cs in stack if kind == "ns" for c in cs]
                for i in range(1, len(full) + 1):
                    namespaces.add(".".join(full[:i]))
            elif kw == "section":
                stack.append(("sec", comps))
            elif (
                stack
            ):  # end [Name]: closes one scope (`end A.B` closes `namespace A.B`)
                stack.pop()
        else:
            for word in m.group("opennames").split():
                if word in _OPEN_STOP:
                    break
                if word.startswith("(") or word.startswith("_"):
                    continue
                namespaces.add(word.strip("()"))
    code = _DOC_IN_ATTR.sub(" ", code)
    return decls, code, namespaces


# --- to_additive names -----------------------------------------------------

# Subset of the word dictionary used by Mathlib's `to_additive` name guessing.
_ADDITIVE_WORDS = {
    "mul": "add",
    "one": "zero",
    "inv": "neg",
    "div": "sub",
    "prod": "sum",
    "pow": "nsmul",
    "npow": "nsmul",
    "zpow": "zsmul",
    "smul": "vadd",
    "finprod": "finsum",
    "tprod": "tsum",
    "multipliable": "summable",
    "monoid": "addMonoid",
    "submonoid": "addSubmonoid",
    "group": "addGroup",
    "subgroup": "addSubgroup",
    "semigroup": "addSemigroup",
    "magma": "addMagma",
    "unit": "addUnit",
    "units": "addUnits",
    "commute": "addCommute",
    "semiconj": "addSemiconj",
    "zpowers": "zmultiples",
    "powers": "multiples",
    "cyclic": "addCyclic",
    "haar": "addHaar",
    "torsion": "addTorsion",
    "action": "addAction",
    "conj": "addConj",
    "opposite": "addOpposite",
}
_CAMEL = re.compile(r"[A-Z][a-z0-9]*|[a-z0-9]+|[^A-Za-z0-9]+")


def _translate_piece(piece):
    target = _ADDITIVE_WORDS.get(piece.lower())
    if target is None:
        return piece
    return target[0].upper() + target[1:] if piece[0].isupper() else target


def additive_name(name):
    """Best-effort guess of the name `@[to_additive]` gives a declaration."""
    return ".".join(
        "".join(_translate_piece(p) for p in _CAMEL.findall(comp))
        for comp in name.split(".")
    )


# --- references -------------------------------------------------------------


def count_references(files, universe):
    """files: iterable of (module, code, namespaces).

    Returns {name: number of files other than its own module mentioning it}.
    """
    referencing = defaultdict(int)
    for module, code, namespaces in files:
        prefixes = [""] + sorted(ns + "." for ns in namespaces)
        hits = set()
        for tok in set(_TOKEN.findall(code)):
            for p in prefixes:
                cand = p + tok
                if cand in universe:
                    hits.add(cand)
        for name in hits:
            if universe[name]["module"] != module:
                referencing[name] += 1
    return dict(referencing)


def iter_source_files(root=config.MATHLIB_DIR):
    for path in sorted((root / "Mathlib").rglob("*.lean")):
        module = str(path.relative_to(root).with_suffix(""))
        yield module, path.read_text(encoding="utf-8")


def build_index(universe, files):
    decls = {}
    parsed = []
    additive_docs = 0
    generated = []
    for module, text in files:
        file_decls, code, namespaces = parse_file(text)
        parsed.append((module, code, namespaces))
        for d in file_decls:
            if d["additive_doc"] is not None:
                additive_docs += 1
            # first definition wins (e.g. a declaration re-opened later is rare)
            decls.setdefault(d["name"], dict(d, module=module))
            if d["to_additive"]:
                generated.append(
                    (
                        additive_name(d["name"]),
                        dict(d, doc=d["additive_doc"], module=module),
                    )
                )
    # generated additive declarations, only where the source has no explicit one
    additive_found = 0
    for name, d in generated:
        if name in universe and name not in decls:
            decls[name] = d
            additive_found += 1
    refs = count_references(parsed, universe)
    index = {}
    for name in universe:
        d = decls.get(name)
        index[name] = {
            "found": d is not None,
            "doc": d["doc"] if d else None,
            "wikidata": d["wikidata"] if d else None,
            "refs": refs.get(name, 0),
        }
    found = sum(1 for v in index.values() if v["found"])
    stats = {
        "source_files": len(parsed),
        "source_decls": len(decls),
        "universe": len(universe),
        "universe_found": found,
        "coverage": found / len(universe) if universe else 0.0,
        "with_doc": sum(1 for v in index.values() if v["doc"]),
        "to_additive_docs": additive_docs,
        "to_additive_matched": additive_found,
    }
    return index, stats


def main():
    universe = load_universe()
    print(f"Universe: {len(universe)} candidate declarations")
    index, stats = build_index(universe, iter_source_files())
    config.DATA_DIR.mkdir(parents=True, exist_ok=True)
    with open(config.SOURCE_INDEX_JSON, "w") as f:
        json.dump({"stats": stats, "declarations": index}, f)
    for k, v in stats.items():
        print(f"  {k}: {v:.1%}" if k == "coverage" else f"  {k}: {v}")
    print(f"Wrote {config.SOURCE_INDEX_JSON}")


if __name__ == "__main__":
    main()
